### ISSUE TITLE
Rely on timezone settings?

### ISSUE THREAD

**Issue by tomkyle** [phmLabs/Smoke#13]
OSX/PHP5.6.7: 
„20%PHP Warning:  strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in phar:///Users/carsten/bin/Smoke.phar/src/whm/Smoke/Rules/Http/Header/Cache/ExpiresRule.php on line 14“
– Not quite sure if the problem sits inside the phar or in front of the computer?

**Comment by phmLabs** [comment]
You have to define your timezone inside the php.ini file. Or use a bootstrap file.

**Comment by tomkyle** [comment]
Mh, solved, thx. Just wonder why I did not get such a warning for two months in this configuration *kopfkratz*
