### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by phmLabs** [phmLabs/Smoke#23]
There schould be a website were everybody can check domains

**Comment by phmLabs** [comment]
Als an alpha version I prepared smoke.phmlabs.com

**Comment by digitalkaoz** [comment]
can we use github pages for that?

**Comment by phmLabs** [comment]
I don't think because we use curl, php, ...

**Comment by digitalkaoz** [comment]
ah a live checker? i can do the basic stuff, templating isnt my domain ;)

**Comment by phmLabs** [comment]
http://smoke.phmlabs.com/app_dev.php/ first version :)

**Comment by digitalkaoz** [comment]
thats enough ;)

**Comment by digitalkaoz** [comment]
i would have used silex...we dont need a full bloating symfony here

**Comment by phmLabs** [comment]
The scan will take sth like 5-10 seconds. The framework will not be the limiting factor.

**Comment by digitalkaoz** [comment]
but maybe your server ;)

**Comment by phmLabs** [comment]
Done.
