### ISSUE TITLE
Uri extraction broken

### ISSUE THREAD

**Issue by phmLabs** [phmLabs/Smoke#29]
http:\/\/connect.facebook.net\/de_DE\/all.js is found:

<script type="text/javascript">(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return}js=d.createElement(s);js.id=id;js.src="http:\/\/connect.facebook.net\/de_DE\/all.js";fjs.parentNode.insertBefore(js,fjs)}(document,"script","facebook-jssdk"));</script>

**Comment by digitalkaoz** [comment]
is this still valid after the document refactoring?

**Comment by phmLabs** [comment]
Seems to work. Closed.
