### ISSUE TITLE
Include-Path in Smoke.php is wrong

### ISSUE THREAD

**Issue by mischka** [phmLabs/Smoke#41]
After installing smoke via composer on my mac I can't start the cli.
The reason is, that the path in the Smoke.php is wrong:

    $loader = include __DIR__.'/../vendor/autoload.php';

correct is (because it's an Symlink)

    $loader = include __DIR__.'/../../../../vendor/autoload.php';

You should handle this like phpunit https://github.com/sebastianbergmann/phpunit/blob/4.6.10/phpunit with a SMOKE_COMPOSER_INSTALL constant.

**Comment by digitalkaoz** [comment]
a PR is welcome ;)
