### ISSUE TITLE
Refactor directory structure

### ISSUE THREAD

**Issue by phmLabs** [phmLabs/Smoke#42]
* Document is html not http
* Where to store listeners?
* Console vs Cli?

**Comment by phmLabs** [comment]
I would store every listener in a plugin directory. 

Plugin/Console/ProgressBar/SfProgressBar.php
Plugin/Reporter/CliReporter.php

@digitalkaoz ok?

**Comment by digitalkaoz** [comment]
mh mapping event-listeners to plugins? why not simply `EventListener` ?

**Comment by phmLabs** [comment]
No, everything that extends the base functionality of Smoke is a plugin. But plugins are included via events.
