### ISSUE TITLE
 The "--num-urls" option does not exist.

### ISSUE THREAD

**Issue by frickelbruder** [phmLabs/Smoke#62]
I tried your example for num-urls. Result:

    Smoke.phar analyse --num-urls="20" test.com

    [RuntimeException]
    The "--num-urls" option does not exist.

Please remove either the option from the documentation or reimplement it again ;-)

Frickelbruder

**Comment by phmLabs** [comment]
"fixed" there was just an typo in the documentation. It's num_urls and not num-urls.
