### ISSUE TITLE
CSS returns false positives

### ISSUE THREAD

**Issue by dsiebel** [phmLabs/Smoke#70]
When analysing our website with [Smoke](https://github.com/phmLabs/Smoke) I saw some false positives regarding (the number of) CSS files on the page:

```bash
Smoke.phar analyse "http://www.trivago.de" -u 1
```

returned

```
Failed tests:

    http://www.trivago.de  coming from
    - Too many (15) css files were found. [rule: _HtmlCssCount]
    - [...]
```

Although there are only **three** CSS files / stylesheets in the initial payload.

I provided a [Pull Request to phmlabs/Html](https://github.com/phmLabs/Html/pull/1) that could fix that.

**Comment by digitalkaoz** [comment]
your PR is merged, did it fix your issue? @dsiebel ?

**Comment by dsiebel** [comment]
@digitalkaoz Sure, that's why I submitted it :wink:
