### ISSUE TITLE
Bug: Correct 404 handling

### ISSUE THREAD

**Issue by phmLabs** [phmLabs/Smoke#76]
The new tend adapter throws an exception when a 404 occurs, this is not what we expect. There must be a response object that we can analyze.

**Comment by phmLabs** [comment]
```php
            try {
                $this->responseCache = $this->httpClient->sendRequests($requests);
            } catch (MultiHttpAdapterException $e) {
                $this->responseCache = $e->getResponses();
                $exeptions = $e->getExceptions();
                foreach ($exeptions as $exception) {
                    $this->responseCache[] = $exception->getResponse();
                }
            }
```

**Comment by digitalkaoz** [comment]
mh no its not the zend-adapter...its an event from the http-adapter...pushing the fix it right now

**Comment by digitalkaoz** [comment]
you should revert your patch...its not the right way...the right way is to dont use the StatusEventSubscriber from the http adapter
