### ISSUE TITLE
Downloaded file broken

### ISSUE THREAD

**Issue by c33s** [phmLabs/Smoke#99]
downloading the file via curl
```
curl -O -LSs http://pharchive.phmlabs.com/archive/phmLabs/Smoke/current/Smoke.phar
```
leads to a file with the sha512 `1F081B22085EE92333914A78CF4E3555DA3A8EBC8A46C82BCE46B4CA6BB1EDA554FAB3E71D6C353A0F631B3EC6CC280F6AED7EB08F2B41AE01F8AB987AB51CD2`

running the file leads to an error:
```
php Smoke.phar --version

Warning: include(phar://C:\foo\Smoke.phar/index.php): failed to open stream: phar error: "index.php" is not a file in phar "C:/foo/Smoke.phar" in C:\foo\Smoke.phar on line 9

Call Stack:
    0.0290    1398728   1. {main}() C:\foo\Smoke.phar:0


Warning: include(): Failed opening 'phar://C:\foo\Smoke.phar/index.php' for inclusion (include_path='phar://C:\foo\Smoke.phar;.;c:\apps\php\include') in C:\foo\Smoke.phar on line 9

Call Stack:
    0.0290    1398728   1. {main}() C:\foo\Smoke.phar:0
````

it looks like there is a versioned url available, i tried to dowloading `wget http://pharchive.phmlabs.com/archive/phmLabs/Smoke/1.18.0/Smoke.phar` and get a file with the hash `B83FA3BB53568A32239A7FACEE54029434512EC812B544FB8A101F1722451398ACFA8E524F174A99E140476C723B062D017814546A5DC40B13E03CA737727E62` but i get the same error on running it

edit: i run php7.1.16x64

**Comment by sebastianneubert** [comment]
I got an error to, if I want to use the phar from pharchive. It seems, that the phar creating process doesn't work anymore. The readme is misleading here.

Just clone the repo, run `composer update` and call the `bin/Smoke.php` if you want to run smoke. Maybe @phmLabs can check, whats going on with the phar builder.

    git clone git@github.com:phmLabs/Smoke.git
    cd Smoke
    composer update
    ./bin/Smoke.php analyse https://www.nytimes.com/

**Comment by c33s** [comment]
@sebastianneubert thanks for the update, the problem is that i would need the versioned phar for my ci, so i can add the hash of the file to check against it.

**Comment by c33s** [comment]
works now. tested with version 1.20.3
